# Generated by Django 2.0.9 on 2018-11-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0002_auto_20181106_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='repository',
            name='url',
        ),
        migrations.AddField(
            model_name='repositorylanguage',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalcontributor',
            name='repositories',
            field=models.ManyToManyField(to='contribution.Repository'),
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='contribution.Repository'),
        ),
        migrations.AddField(
            model_name='commit',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contribution.ExternalContributor'),
        ),
    ]
