# Generated by Django 2.0.9 on 2018-11-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0003_auto_20181125_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='url',
        ),
    ]
