# Generated by Django 2.0.9 on 2018-11-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0003_auto_20181125_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.IntegerField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='contribution.Repository')),
            ],
        ),
        migrations.RemoveField(
            model_name='commit',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='username',
        ),
        migrations.DeleteModel(
            name='Commit',
        ),
    ]
