# Generated by Django 2.1.8 on 2019-06-07 11:37

import apps.authentication.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_auto_20190602_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[apps.authentication.validators.validate_rfid], verbose_name='RFID')),
                ('nfc', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[apps.authentication.validators.validate_rfid], verbose_name='NFC')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Strekkode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Studentkort',
                'ordering': ('rfid', 'nfc'),
                'permissions': (('view_studentcard', 'View Student Card'),),
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='StudentCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntnu_username', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='NTNU-brukernavn')),
                ('student_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Studentnummer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Studentinformasjon',
                'ordering': ('ntnu_username',),
                'permissions': (('view_studentcredentials', 'View Student Credentials'),),
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
    ]
