# Generated by Django 2.1.8 on 2019-06-07 12:37

from django.db import migrations

"""
Create StudentCard and StudentCredentials for existing users.
Load new models with data from existing fields from the user model.
"""


def load_data(apps, schema_editor):
    User = apps.get_model('authentication', 'OnlineUser')
    StudentCard = apps.get_model('authentication', 'StudentCard')
    StudentCredentials = apps.get_model('authentication', 'StudentCredentials')

    for user in User.objects.all():
        try:
            card = StudentCard.objects.get(user=user)
        except StudentCard.DoesNotExist:
            card = StudentCard.objects.create(user=user)
        card.rfid = user.rfid
        card.save(update_fields=['rfid'])

        try:
            credentials = StudentCredentials.objects.get(user=user)
        except StudentCredentials.DoesNotExist:
            credentials = StudentCredentials.objects.create(user=user)
        credentials.ntnu_username = user.ntnu_username
        credentials.save(update_fields=['ntnu_username'])


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_studentcard_studentcredentials'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
